version: '3'
services:
  app:
    container_name: docker-node-mongo
    build: .
    environment:
      - MONGO_URI=localhost
      - MONGO_DB
      - LISTEN_PORT=3006
    ports:
      - '3006:3006'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
